@host=http://localhost:3000
@customerpath=/api/customer
@logoutpath=/api/logout
@refreshpath=/api/refresh
@feedbackpath=/api/feedbacks
@refreshtoken=eyJhbGciOiJIUzI1NiJ9.MQ.Y25nTfjhdc3QfI5mfAWvYstjxdRoD5wNfofxiVG_sD0
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiZGV2Iiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzI4Mjg0OTE2LCJleHAiOjE3MjgzNzEzMTZ9._VAnfBjF4IeoJgMsRudkbO6J5afIDe9zi42M5gEvy-g

GET {{host}}

###
# signup
POST {{host}}{{customerpath}}/signup
Content-Type: application/json

{
  "username": "dev",
  "email": "a@b.com",
  "password": "developer"
}

###
# login
POST {{host}}{{customerpath}}/login
Content-Type: application/json

{
  "username": "dev",
  "password": "developer"
}

###
# refresh
POST {{host}}{{refreshpath}}
Content-Type: application/json

{
  "refresh": "{{refreshtoken}}"
}

###
#logout
POST {{host}}/{{logoutpath}}
Content-Type: application/json

{
  "action": true
}

###
# get feedback
GET {{host}}{{feedbackpath}} HTTP/1.1
Authorization: Bearer {{access}}
