@host=http://localhost:3000
@customer-path=/api/customers
@logout-path=/api/logout
@refresh-path=/api/refresh
@feedback-path=/api/feedbacks
@owner-path=/api/owners
@customer-refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODc0NjU3MSwiZXhwIjoxNzI5MzUxMzcxfQ.ptby-nSgJJUDBkgCu8MdNWt_1Ugu9XFeFSYf8crwCG0
@customer-access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiZGV2Iiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzI4NzQ2NTcxLCJleHAiOjE3MzEzMzg1NzF9.5HffHWkVx3o9gJCMxajrh74m2qk_0VV787g3TrUooiA
@owner-refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODc1MDg2NSwiZXhwIjoxNzI5MzU1NjY1fQ.VGDx4Orh3qEL1HgRQu-YPkpdohIMLZmhgFYhyXkmFtw
@owner-access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoib2RvIiwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzI4NzUwODY1LCJleHAiOjE3MzEzNDI4NjV9.iFLvY1vMvt8AU8BYBZUQ8W-HbUtOv20q-WqIDNyXbHo
@admin-refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg3NTg0ODIsImV4cCI6MTczMTM1MDQ4Mn0.7XiPQE4ivhmZ7pZrcpsNWE_-rs9u5Aj2bQBMiUiW3RA
@admin-access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg3NTg0ODIsImV4cCI6MTcyOTM2MzI4Mn0.ZT4b6fC8zCWn_RPye2NbLSgfGd1Afw4eGoXplXFC84g

GET {{host}}

###
# signup
POST {{host}}{{customerpath}}/signup
Content-Type: application/json

{
  "username": "dev",
  "email": "a@b.com",
  "password": "developer"
}

###
# login
POST {{host}}{{customerpath}}/login
Content-Type: application/json

{
  "username": "dev",
  "password": "developer"
}

###
# refresh
POST {{host}}{{refreshpath}}
Content-Type: application/json

{
  "refresh": "{{refreshtoken}}"
}

###
#signup as owner
POST {{host}}/{{ownerpath}}
Content-Type: application/json

{
  "username": "odo",
  "email": "odo@dukadan.com",
  "password": "dukadan"
}

###
# get feedback
GET {{host}}{{feedbackpath}} HTTP/1.1
Authorization: Bearer {{access}}
