@host=http://localhost:3000
@customerpath=/api/customers
@logoutpath=/api/logout
@refreshpath=/api/refresh
@feedbackpath=/api/feedbacks
@ownerpath=/api/owners
@refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiZGV2Iiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzI4NTA2Nzc1LCJleHAiOjE3MzEwOTg3NzV9.cq17GUmN9REb6QVQanNxSljNZF_6dpc-Qewhpa4wzaw
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODUwNjc3NSwiZXhwIjoxNzI5MTExNTc1fQ.GoUaNtxLExxMtAldjo9Q0UejPOaPN8ZTiv-iUSjf9Hc

GET {{host}}

###
# signup
POST {{host}}{{customerpath}}/signup
Content-Type: application/json

{
  "username": "dev",
  "email": "a@b.com",
  "password": "developer"
}

###
# login
POST {{host}}{{customerpath}}/login
Content-Type: application/json

{
  "username": "dev",
  "password": "developer"
}

###
# refresh
POST {{host}}{{refreshpath}}
Content-Type: application/json

{
  "refresh": "{{refreshtoken}}"
}

###
#signup as owner
POST {{host}}/{{ownerpath}}
Content-Type: application/json

{
  "username": "odo",
  "email": "odo@dukadan.com",
  "password": "dukadan"
}

###
# get feedback
GET {{host}}{{feedbackpath}} HTTP/1.1
Authorization: Bearer {{access}}
